Started logging messages at Sat Oct 11 23:09:42 2014
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 8 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 72
Info:            Created 
Info:        Working on 73
Info:            Created 
Info:        Working on 100
Info:            Created 
Info:        Working on 124
Info:            Created 
Info:        Working on 126
Info:            Created 
Info:        Working on 103
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 92
Info:            Created 
Info:        Working on 120
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 118
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 135
Info:            Created 
Info:        Working on 30
Info:            Created 
Info:        Working on 140
Info:            Created 
Info:        Working on 49
Info:            Created 
Info:        Working on 136
Info:            Created 
Info:        Working on 78
Info:            Created 
Info:        Working on 108
Info:            Created 
Info:        Working on 129
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sat Oct 11 23:09:42 2014
